### PR TITLE
Update SetupFUFramework.ps1

### PR DESCRIPTION
**Pull request by tokar04**
Configmgr 2010 don't like it for some reason

PropertyType = [Microsoft.ConfigurationManagement.DesiredConfigurationManagement.FileFolderProperty]::Version
ExpressionOperator = [Microsoft.ConfigurationManagement.Cmdlets.Dcm.Commands.RuleExpressionOperator]::GreaterEquals

### CODE REVIEW

**Comment by AdamGrossTX** [comment]
Thanks for the update - I'll need to test against older versions and ensure this change doesn't break them. There are a few buggy things with the PowerShell cmdlets that I had to work around.

**Comment by tju-pwsh** [comment]
I am having this issue as well. I worked around it by outcommenting the few lines regarding the application at line 365 and handling the application manually. SCCM version 2010 with latest hotfixes

EDIT: It works fine with the commit tokar04 provided.

 + Creating new Application Feature Update - Client Content. X
########################################################
The following error occurred:
 + Cannot bind parameter 'ExpressionOperator'. Cannot convert value "GreaterEquals" to type "Microsoft.ConfigurationManagement.Cmdlets.Dcm.Commands.FileFolderRuleExpressionOperator" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration values are "IsEquals;NotEquals;
GreaterThan;LessThan;Between;GreaterEquals;LessEquals;OneOf;NoneOf".
 + Line: 365
########################################################
New-CMDetectionClauseFile : Cannot bind parameter 'ExpressionOperator'. Cannot convert value "GreaterEquals" to type "Microsoft.ConfigurationManagement.Cmdlets.Dcm.Commands.FileFolderRuleExpressionOperator" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration value
s are "IsEquals;NotEquals;GreaterThan;LessThan;Between;GreaterEquals;LessEquals;OneOf;NoneOf".
At C:\Temp\SetupFUFramework.ps1:365 char:39
+     $cla3 = New-CMDetectionClauseFile @SetupDiagDetectionClause
+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-CMDetectionClauseFile], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.ConfigurationManagement.Cmdlets.Dcm.Commands.NewDetectionClauseFile

**Comment by AdamGrossTX** [comment]
Thanks for the info. Sorry, I haven't had time to re-test with 2010. I'll see if I can get it updated soon.

**Comment by AdamGrossTX** [comment]
I was able to replace the failing property with a supported one 

`ExpressionOperator = [Microsoft.ConfigurationManagement.Cmdlets.Dcm.Commands.FileFolderRuleExpressionOperator]::GreaterEquals`

**Pull request closed without merging**
